<?php

namespace Database\Seeders;

use App\Models\Supplier;
use Illuminate\Database\Seeder;

class SupplierSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $suppliers = [
            'AADI SHAKTI TECHNICAL SERVICES LLC',
            'ABDUL NAVEED ABDUL HAMID ABDUL HAMID',
            'ACOUSTIC.AE FZC LLC',
            'ADAN GEN TR LLC SOLE PROPRIETORSHIP',
            'AHLAN GENERAL TRADING LLC',
            'AL ADIL GENERAL TRADING L.L.C',
            'AL AHAD CURTAINS TEX & FURNITURE TR LLC',
            'AL AJWA BLDG MAT TR. LLC',
            'AL DIRHAM ALUMINIUM & GLASS CONT',
            'AL HABIB GARMENTS W/SHOP L.L.C',
            'Al Habtoor Motors Co. L.L.C',
            'AL HAJAR AL DHAHABI BUILDING MATERIALS SALE L.L.C',
            'Al Jusoor Bldg. Mat. Tr. LLC',
            'Al Mintasir Paints & Decor Mat. Tr.',
            'Al Muadalah Decor Mat. Tr. LLC',
            'AL QARHOUD CARPENTRY',
            'AL QARIB WOOD INDUSTRY LLC',
            'AL RAMADI PAINTS TRADING L L C',
            'AL SARH AL AALI BLDG.MAT.TRADING L.L.C',
            'AL SAWARY TRADING CO. LLC',
            'AL WISAM AL FADHI BLDG. EQUIP. RENT LLC',
            'AL YAMAMA AL BAYDA FURNITURE L.L.C',
            'ALAR SOLUTIONS ADVERTISING REQUISITES TRADING LLC',
            'Al-Futtaim Motors Company LLC',
            'ALHIND & MIDDLE EAST TRAVEL LLC',
            'AL-NASSAJ ALASRI TEXTILE TRADING LLC',
            'Al-Sousi TR CO LLC',
            'AL-SOUSI TRADING CO LLC',
            'ALZAN BUILDING MATERIALS TRADING LLC',
            'ANCHOR ALLIED FACTORY LLC.',
            'APT CONSTRUCTION EQUIPMENT RENTAL LLC',
            'ARAK INDUSTRIAL L.L.C',
            'Areeka Events Organizing Services LLC',
            'ARKAN GENERAL TRADING L.L.C',
            'BAB AL BAHAR BLDG MAT TR',
            'BAGNO DESIGN L.L.C',
            'Best Gifts Centre',
            'BMAA TECHNICAL SERVICES CONTRACTING L.L.C',
            'CHABROS TIMBER TRADING LLC',
            'CONCORD HOMES LIGHTING - FZCO',
            'CREATIVITY WAY GENERAL TRADING LLC',
            'DAR AL ARAB PRINTING & STATIONARY L.L.C',
            'DUBAI TIMBER BUILDING MAT.TR.LLC.',
            'EARLY WARNING FIRE SYSTEMS FIX. & MAINT.L.L.C',
            'EMILAM INDUSTRIES L.L.C',
            'EMIRATES ICA BLDG.MAT.LLC',
            'EUROPEAN WOOD PRODUCTS TRADING L.L.C',
            'EVI PAINTS & COATINGS',
            'FABRIC LIBRARY FZCO',
            'FAKHRI TOOLS & WORKSHOP MATERIALS TRADING L.L.C',
            'FAKHRUDDIN KADERBHAI TRADING CO LLC',
            'FALAJ AL QABAIL BLDG MAT & PAINTS TR LLC',
            'Fan Alnaht Draw & Sign',
            'Fern Interior Decoration LLC',
            'FINE TOOLS TRADING LLC',
            'FIRSTBIT TECHNOLOGIES L.L.C',
            'FRITZ KOHL MIDDLE EAST LLC',
            'FUTURE CHOICE MACHINERY TRADING LLC SP',
            'GALAXY EXTRUTECH POLYMER INDUSTRY LLC',
            'Gemini Building Materials LLC',
            'GHAZALI KHAN CARPENTRY LLC',
            'GHULAM ABBAS CONST.EQUIP. & MACHINES TR.',
            'GLOBAL YARD PLYWOOD INDUSTRIES LLC',
            'HADAEQ ALBAMBU ARTIFICIAL FLOWERS TRADING L.L.C.',
            'HAFELE MIDDLE EAST TRADING L.L.C.',
            'HALA BUILDING MATERIAL TRADING',
            'HANDS MIDDLE EAST LLC',
            'HAROON ENG.MAT.MARKETING CO.LLC',
            'Hilti Emirates LLC',
            'Holy Quran Academy',
            'HOLZCRAFT MACHINERY TRADING L.L.C',
            'HUSAINI AJMER BUILDING MATERIAL TRADING LLC',
            'INARA INTERNATIONAL LIGHTING EQUIP TR.LLC',
            'INFOCUS GLASS AND ALUMINIUM WORKS LLC',
            'INFOME TECHNOLOGIES L.L.C',
            'INNOVATIVE HIRING LLC.',
            'IRFAN TECHNICAL SERVICES',
            'JILPHAR TOURS L.L.C',
            'KALLEGRA INDUSTRIES L.L.C',
            'LOGIC OFFICE EQUIPMENTS L.L.C',
            'LPFLEX BASE INDUSTRY L.L.C',
            'LUMBER WORLD BUILDING MATERIAL TRADING LLC',
            'LUNA & SUN (FZE)',
            'MAS PAINTS & CHEMICALS INDUSRTY',
            'MD RAFIQUL & HELAL UDDIN ELECTRICALS TRADING L.L.C',
            'MD RAFIQUL ELECTRICALS TRADING L.L.C',
            'Media Building Materials LLC SB',
            'MEDIA BUILDING MATERIALS TRADING LLC SHJ.BR',
            'METALLIC EQUIPMENT HOLDING L.L.C',
            'MODERN TOUCHES FIRE R. & R. MAT.TRD.LLC',
            'Mohd. Al Qama Building Materials Trading L.L.C. Br.',
            'MUHAMMAD ANSAR MUHAMMAD ASHRAF',
            'NAJMAT AL ZAIN ALUMINIUM & GLASS CONT LLC',
            'NAJMAT KASHMEER MARBLE & GRANITE TR.LLC.',
            'NEWTON GENERAL TRADING L.L.C',
            'NEXA GENERAL TRADING LLC FZE',
            'Nexel Computers & Requisites Trading LLC',
            'NOOR AL BASMAH READYMADE GAR TR.LLC',
            'ORNATE WOOD MANUFACTURING LLC',
            'OTAL L.L.C',
            'PLANET ECO BUILDING MATERIALS L L C',
            'RABIA SHAKEEL GENERAL TRADING LLC',
            'RANDOM  WORKS TECHNOLOGY',
            'REALITY BUILDING MATERIALS TRADING LLC',
            'ROYAL MARBLE BUILDING MATERIALS TRADING L.L.C',
            'RWT SYSTEMS LLC',
            'S T M BUILDING & CONTRUCTION MATERIALS TRADING CO. L.L.C',
            'SADEEN FOAM & FURNITURE INDUSTRY (L.L.C)',
            'SEVEN WONDERS ELECTRONICS TRADING LLC',
            'SHAJI AUTO PAINTS TRADING LLC',
            'SHAMS AL SABAH GEN. TRD. LLC',
            'SHARPTECH ELECTRICAL EQUIPMENT MAINTENANCE WORKSHOP',
            'SILVER CHAIR FURNITURE LLC',
            'SILVER STAR ELECTRONICS LLC.',
            'SIRIUS LLC',
            'Smart Point Auto New Spare Parts Tr. L.L.C',
            'Space Builders LLC',
            'SPARK WORLD LIGHTING ELECTRICAL FITTINGS TRADING LLC',
            'SUKOON INSURANCE PJSC',
            'TAREEQ AL MUSTAQBAL STEEL WORKSHOP L.L.C',
            'TAREEQ AL SAJAA BLDG EQUIP RENTAL & TRADING',
            'TECHNOMAN BLDG.MAT.TR L.L.C',
            'Technoman Building  Material Trading',
            'TIMBER VALLEY TRADING L.L.C',
            'TOP LINE BUILDING MATERIALS CO.LLC',
            'TYCHE GULF OIL & GAS EQUIPMENT TRADING L.L.C',
            'ULTIMATE HARDWARE SOLUTIONS LLC',
            'UNILAM WOOD INDUSTRIES L.L.C',
            'UNITED DIESEL LLC',
            'VRS Technologies LLC',
            'WHITE CROWN TECH. CONT',
            'WURTH GULF (L L C)',
            'YORK FURNISHING TEXTILES FZE',
            'YUSUF NOMAN BLDG.MAT.TR.',
            'ZAHRH ESTHER HARDWARE TRADING LLC',
            'ADAMJEE INSURANCE COMPANY LIMITED',
            'AL AMANAT RUKN ELECTRIC WARE TRDG L.L.C',
            'AL BARIO TECHNICAL SERVICES',
            'AL FAHS W.SHOPS TOOLS MAINT',
            'AL FARAH CARPENTRY & DECORATION LLC',
            'AL FURSAN METAL INDUSTRIES L.L.C SP',
            'AL JESSOUR BLDG. MAT. TR. LLC- SOLE PROPRIETORSHIP',
            'AL KHIDMA BLDG.MAT.TR.LLC',
            'AL MASAR ELECTRONICS TRADING',
            'AL MAZRAA TECH. CONT',
            'AL MUSBAH AL THAHBI MOBILE PHONE & ELECTRONICS TR.',
            'AL RAHMA BUILDING MATERIAL TRADING',
            'AL RAWASI INTERIOR DISGN',
            'AL RAYYAN CARPENTRY L.L.C.SP',
            'AL RMOOL BUILDING CLEANING SERVICES',
            'AL SALIM ALUMINUM IND.L.L.C',
            'AL SANA TECHNICAL SOLUTIONS LLC',
            'AL WISAM TR.CO.LLC',
            'AMJAD NAZWA BLDG.CONT',
            'AQUATIC STAR CARPENTRY WORKS',
            'B S A ELECTROMECHANICAL SERVICES',
            'BAIT AL ALMAS LATHE WORKSHOP L.L.C',
            'CASH SUPPLIER',
            'CLICK TIMBER TECHNICAL SERVICES',
            'DAR ALEZ TECHNICAL SERVICES',
            'DAVINDER SINGH BLDG.MAT.TR.LLC',
            'DENOLEX POLYMERS LLC',
            'DINCO TRADING CO.LLC',
            'DK DECORATION MATERIAL FZCO',
            'DM SAFETY SERVICES LLC',
            'EGARDENKART FZE',
            'ELECTRICAL LIGHTING COMPANY L.L.C',
            'ETQAN ELTAMEER TECHNICAL SERVICES EST.',
            'FINEWOOD BUILDING MATERIALS TRADING L.L.C',
            'FOUR K BUILDING MATERIALS LLC',
            'FROMA GENERAL TRADING L.L.C',
            'GALLERY INTERIOR DECOR',
            'GERMAN TECH MACHINERY LLC',
            'GREEN HILLS MARBLE LLC',
            'HOSSAM MOHAMMED MAHMOUD TECHNICAL SERVICES L.L.C',
            'HUSSAIN MOHD.FURNITURE',
            'INDIGA SOLID SURFACE FZ LLC',
            'INFORMAP TECHNOLOGY CENTER L.L.C',
            'ITALCO MIDDLE EAST TRADING LLC',
            'JAYCHAND TECHNICAL SERVICES CO. L.L.C',
            'KHF AUTOMOTIVE SERVICE LLC',
            'KINZA MINAL TECHNICAL SERVICES CO.',
            'LANDMARK RETAIL INVESTMENT CO.LLC',
            'LASTING LONG ENTERPRISES FZCO',
            'Leadermac Machinery Trading LLC',
            'MAISAM TRADING L.L.C',
            'MALIK BROTHERS FZE LLC',
            'MALIYA PAINTS TR LLC',
            'MARYAM ASEFI TECHNICAL SERVICES L.L.C',
            'MASAR AL JOUD TECHNICAL SERVICES',
            'METAL BUREAU MIDDLE EAST L.L.C-FZ',
            'MILANO PAINT INDUSTRY',
            'MOBILITY GENERAL TRADING L.L.C',
            'MOHAMED RASHID MOHAMED AUTO.MAIN.W.SHOP',
            'PIONEER DEFINITION TECHNICAL SERVICES LLC',
            'POWER RENTAL SOLUTIONS FZE',
            'POWERZONE SALE SPARE PARTS FOR MACHINES & ENGINES LLS SP',
            'PRIMITIVE WORLD TRADING L.L.C',
            'RAINBOW PRINTING IND.LLC (R.P.I)',
            'RED ROAD AUTO MAINT',
            'RITVER PAINTS MANUFACTURING L.L.C',
            'RUKN AL MIZAN MACHINERY REPAIRING',
            'SABIN PLASTIC INDUSTRIES L.L.C',
            'SEDANA TRADING CO. L.L.C',
            'SHARJAH ENVIRONMENT CO. LLC BEEAH',
            'SILVER THREAD SEWING TR.CO.L.L.C',
            'SUMI CRAFT INTERIOR DESIGN',
            'TAREEQ AL QASMIA GEN TRANSPORT L.L.C',
            'TATWEER BAITK TECHNICAL SERVICES LLC',
            'TRIENT FIRE RESISTANT DOORS TRADING',
            'VARAHI UNIFORMS L.L.C',
            'WESAM AL JAZIRA TECHNICAL WORKS L.L.C',
            'ZUBAIDAH ALUMINIUM & GLASS CONT.',
        ];

        // Insert suppliers in batches
        $batchSize = 50;
        $batches = array_chunk($suppliers, $batchSize);

        foreach ($batches as $batch) {
            foreach ($batch as $supplierName) {
                Supplier::firstOrCreate(
                    ['name' => $supplierName],
                    [
                        'name' => $supplierName,
                        'is_active' => true,
                    ]
                );
            }
        }

        $this->command->info('✅ ' . count($suppliers) . ' suppliers seeded successfully!');
    }
}
